version: '3.1'
services:
  mysql:
    image: 'mysql:8.0'
    working_dir: /application
    environment:
      MYSQL_DATABASE: 'moodle'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    volumes:
      - '.:/application'

  nginx:
    image: 'nginx:alpine'
    working_dir: /application
    ports:
      - '82:80'
    volumes:
      - '.:/application'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - mysql
      - php

  php:
    build: docker/php
    working_dir: /application
    volumes:
      - '.:/application'

  node:
    image: "node:19"
    working_dir: /application
    volumes:
      - '.:/application'